### ISSUE TITLE
Question: Using Window Title for foobar2000, any way I can send playback time and song duration to Tuna?

### ISSUE THREAD

**Issue by NafenX** [nschloe/tuna#168]
I'm using foobar2000 along with the YouTube Source plugin in order to play songs from YouTube in there, and I've formatted my foobar2000 Window Title so it will say "<artist> - <song title> - <playback time>/<song duration>" and was wondering if there is any way to send the playback time and song duration info to Tuna to use with the progress bar source etc. 

As it stands, right now the Tuna text source will show the full title bar but what I am hoping for is to cut the playback time and song duration out of the title and have it be used in the progress bar source.

**Comment by nschloe** [comment]
Wrong repo?

**Comment by NafenX** [comment]
Yeah definitely, my bad! I was on the right one before and I have no idea how I got to this one!
