### ISSUE TITLE
Support fluid-width browser windows

### ISSUE THREAD

**Issue by eric-wieser** [nschloe/tuna#18]
It seems a shame to have a wide monitor, but have tuna only use the narrow center of it.

Setting `class="container-fluid"` is just the tip of the iceberg here.

Most of my patches so far have come about as a result of looking into this, and getting a better mental model for d3js

**Comment by nschloe** [comment]
Do you mean that the icicle graph should rescale as you rescale the width of the browser window?

**Comment by eric-wieser** [comment]
Yes

**Comment by nschloe** [comment]
Not sure if this is feasible. After all, the browser would have to redraw every box every so and so many milliseconds. If you're looking at ordinary `width="100%"` elements, no browser I know of redraws upon window size change. The user has to reload to page to adapt widths. Same with tuna right now. That said, we could give all `rect`s relative widths, in case a browser supports redrawing upon window resize one day.
