### ISSUE TITLE
Look for tracebacks in the log file

### ISSUE THREAD

**Issue by eric-wieser** [nschloe/tuna#3]
Right now I get a failure of `assert len(items) == 3` if the profile data from python ends up with a traceback within it. It would be nice if the error message were clearer.

**Comment by nschloe** [comment]
Ah, right. Could you append an example profile so I can play around with it?

**Comment by eric-wieser** [comment]
Sure:
```
$ cat nope.py
import os
import sys
raise ValueError("Not a chance")
$ python3.7 -X importtime nope.py 2> import.log
$ cat import.log
import time: self [us] | cumulative | imported package
import time:       124 |        124 | zipimport
import time:       708 |        708 | _frozen_importlib_external
import time:       113 |        113 |     _codecs
import time:      1018 |       1130 |   codecs
import time:      1080 |       1080 |   encodings.aliases
import time:      2682 |       4891 | encodings
import time:       619 |        619 | encodings.utf_8
import time:        96 |         96 | _signal
import time:       610 |        610 | encodings.latin_1
import time:        65 |         65 |     _abc
import time:       656 |        720 |   abc
import time:       760 |       1479 | io
import time:       105 |        105 |   _locale
import time:       805 |        909 | _bootlocale
import time:       494 |        494 | encodings.cp1252
import time:       105 |        105 |       _stat
import time:       707 |        811 |     stat
import time:       444 |        444 |       genericpath
import time:      1382 |       1826 |     ntpath
import time:      1543 |       1543 |     _collections_abc
import time:      1304 |       5482 |   os
import time:       582 |        582 |   _sitebuiltins
import time:       773 |        773 |   sitecustomize
import time:       293 |        293 |   usercustomize
import time:      1787 |       8914 | site
Traceback (most recent call last):
  File "nope.py", line 3, in <module>
    raise ValueError("Not a chance")
ValueError: Not a chance
```

**Comment by eric-wieser** [comment]
I think you should be filtering for lines that start `import time:` and ignoring all the rest

**Comment by nschloe** [comment]
Hm, perhaps including this wasn't a good idea. Now we have a situation where tuna silently produces an incomplete ("wrong") result where before it at least crashed. Perhaps we can make sure it exits more gracefully if the file cannot be parsed properly.

**Comment by eric-wieser** [comment]
#14 was still correct, because it means it no longer fails if the module imported writes to `sys.stderr`. Arguably detecting whether the import crashed isn't `tuna`s problem anyway - the user should be checking that when they invoke python
```python
python36 -X importtime -c 'import mymodule' 2> import.log && tuna import.log || {echo "failed"; exit 1; }
```

**Comment by nschloe** [comment]
> #14 was still correct, because it means it no longer fails if the module imported writes to sys.stderr.

Isn't this already an indication of something going, i.e., something that requires user attention?

Btw
```
python36 -X importtime
```
This works??

**Comment by eric-wieser** [comment]
That was supposed to be 37

> Isn't this already an indication of something going, i.e., something that requires user attention?

Could just be a warning printed to stderr. Perhaps tuna should just print out the lines it doesn't recognize?

**Comment by nschloe** [comment]
> Perhaps tuna should just print out the lines it doesn't recognize?

I like that.
