### ISSUE TITLE
Cant read Profile done with importtime

### ISSUE THREAD

**Issue by Thomasillo** [nschloe/tuna#32]
```
$ tuna profile.data 
Traceback (most recent call last):
  File "/Users/Thomas/.local/miniconda3/envs/4cast_37/bin/tuna", line 11, in <module>
    sys.exit(main())
  File "/Users/Thomas/.local/miniconda3/envs/4cast_37/lib/python3.7/site-packages/tuna/cli.py", line 33, in main
    start_server(args.infile, args.browser)
  File "/Users/Thomas/.local/miniconda3/envs/4cast_37/lib/python3.7/site-packages/tuna/main.py", line 172, in start_server
    data = read(prof_filename)
  File "/Users/Thomas/.local/miniconda3/envs/4cast_37/lib/python3.7/site-packages/tuna/main.py", line 28, in read
    return read_import_profile(filename)
  File "/Users/Thomas/.local/miniconda3/envs/4cast_37/lib/python3.7/site-packages/tuna/main.py", line 125, in read_import_profile
    self_time = int(items[0])
ValueError: invalid literal for int() with base 10: 'self [us]'
```

File profile.dat starts with
```
import time: self [us] | cumulative | imported package
import time:       151 |        151 | zipimport
import time:       685 |        685 | _frozen_importlib_external
import time:        81 |         81 |     _codecs
import time:       619 |        700 |   codecs
import time:       495 |        495 |   encodings.aliases
```

**Comment by nschloe** [comment]
Please attach the entire file so I can reproduce the error.

**Comment by Thomasillo** [comment]
I looked through the file as well. It is in some places interspersed with loggings and warnings, this might be the reason. However, with the information coming from stderr . This is probably not so unusual..

Anyway, here is the file. Thanks for the help. I appreciate that.


[importprofile.txt](https://github.com/nschloe/tuna/files/2407711/importprofile.txt)

**Comment by nschloe** [comment]
I checked out the file and found there are two lines
```
import time: self [us] | cumulative | imported package
```
Usually there's only one at the top of the file. Got something fixed up?

**Comment by Thomasillo** [comment]
Hmm, not that I know of. 
Actually I tried removing that line which gives another error. About the levels being inconsistent.
I have no idea what could be the cause of that line.
Maybe some threaded invocations in some imports (who does stuff like this?) But thats just speculative.

**Comment by nschloe** [comment]
Maybe. I have no clue either. Looks like the file is borked.
