### ISSUE TITLE
What itch does Tuna scratch?

### ISSUE THREAD

**Issue by maphew** [nschloe/tuna#35]
The readme says Tuna is inspired by the awesome SnakeViz, which in turn was inspired by RunSnakeRun. I'm new to the territory and don't know anything about any of these. After a brief look at each I can see why SnakeViz exists; RunSnakeRun hasn't been updated for several years and it's graphical presentation looks pre-schoolish to current eyes. I don't see something similar for Tuna v SnakeViz, which has a community, good presentation, and development activity over time. In other words, what itch does Tuna scratch? (Genuinely curious).

**Comment by nschloe** [comment]
In many cases, the visual representation of snakeviz is simply wrong. See the main readme of tuna for an example. The complications arise from the fact that python's profiler doesn't give all the information necessary to build a timed call tree.

On top of that, tuna much simplifies the code.

**Comment by maphew** [comment]
Thanks, that helps.  

"Main readme"? Is there another readme besides the one at the top? I don't see anything about SnakeViz showing wrong information. Oh, you mean the bit about _"tuna only displays the part of the timed call tree that can be deduced from the profile"_? It might be useful to extend that to mention that SnakeViz doesn't do that (and perhaps other profile visualizers as well, assuming that's true).

**Comment by nschloe** [comment]
I think https://github.com/jiffyclub/snakeviz/issues/112 is enough. I feel it's bad style to talk about errors in other software packages in the readme.

**Comment by maphew** [comment]
Yeah, I get that. It's bad form to call out other's failings and build up your own at the same time. I wouldn't have found the information without asking and then you referencing a closed issue though. ... Anyway. not trying to be argumentative or re-open the issue. The main point was it would be good to have move info to show curious passers-by why this project might be interesting and worth looking at.

Thanks for building this and sharing tuna. I'm enjoying my exploration with it so far.

**Comment by nschloe** [comment]
I'll think about adding something low-profile to the readme once I'm back home. Thanks for the suggestion!
