### ISSUE TITLE
Color builtin modules differently

### ISSUE THREAD

**Issue by eric-wieser** [nschloe/tuna#5]
Could check for membership in `sys.builtin_module_names`

**Comment by nschloe** [comment]
That list is
```
('_ast',
 '_bisect',
 '_blake2',
 '_codecs',
 '_collections',
 '_datetime',
 '_elementtree',
 '_functools',
 '_heapq',
 '_imp',
 '_io',
 '_locale',
 '_md5',
 '_operator',
 '_pickle',
 '_posixsubprocess',
 '_random',
 '_sha1',
 '_sha256',
 '_sha3',
 '_sha512',
 '_signal',
 '_socket',
 '_sre',
 '_stat',
 '_string',
 '_struct',
 '_symtable',
 '_thread',
 '_tracemalloc',
 '_warnings',
 '_weakref',
 'array',
 'atexit',
 'binascii',
 'builtins',
 'errno',
 'faulthandler',
 'fcntl',
 'gc',
 'grp',
 'itertools',
 'marshal',
 'math',
 'posix',
 'pwd',
 'pyexpat',
 'select',
 'spwd',
 'sys',
 'syslog',
 'time',
 'unicodedata',
 'xxsubtype',
 'zipimport',
 'zlib')
```
missing things like `argparse`, `datetime` etc. Hm.

**Comment by nschloe** [comment]
I've simply hardcoded the list of built-in modules now. Hopefully, we'll find a more aesthetically pleasing solution in the future.

**Comment by eric-wieser** [comment]
That list is missing `_ctypes`, `_bz2`, and a few others. Could potentially depend on https://pypi.org/project/stdlib-list/, but that adds the need for network access.

**Comment by nschloe** [comment]
It appears that https://pypi.org/project/stdlib-list is unmaintained. Crucially, Python 3.7 isn't supported (yet?). I guess there's no way around us maintaining our own lists unfortunately. And I'm not too sure what to think about adding private modules to the list...

**Comment by eric-wieser** [comment]
@nschloe: I doubt it needs any maintenance - all it seems to do is scrape the sphinx data from the python docs. As long as the sphinx urls remain the same, it should work for all future python versions

**Comment by nschloe** [comment]
Ah, I'd been looking at https://github.com/jackmaney/python-stdlib-list/tree/master/stdlib_list/lists.

**Comment by eric-wieser** [comment]
Hmm, I think you're right. Looks like the sphinx script is just used to generate those lists at commit-time. Probably fairly straightforward to rerun `fetch`, and create a PR with the 3.7 defs.

**Comment by nschloe** [comment]
> Probably fairly straightforward to rerun fetch, and create a PR with the 3.7 defs.

I think so. I've submitted an issue, let's see if the developer shows up sometime.
