### ISSUE TITLE
Add filename to html title

### ISSUE THREAD

**Issue by luccaportes** [nschloe/tuna#56]
Hi, do you think it is a good idea to add the filename of the profile log to the title of the HTML page? 

It would be useful when analyzing multiple files at the same time. Now it gets very confusing:

![image](https://user-images.githubusercontent.com/14240052/69651078-4cc9ab80-104e-11ea-99d1-67f1cc46a67a.png)

I thought it could be something like "tuna - filename".

I can do that if you agree.

**Comment by nschloe** [comment]
Do it.

**Comment by nschloe** [comment]
Fixed via #57.
