### ISSUE TITLE
almost empty profile?

### ISSUE THREAD

**Issue by ensonic** [nschloe/tuna#63]
I generated the profile on a arm device (running debian jessie), using python3.4 and the command from your readme: python3 -mcProfile -o /tmp/program.prof <myprog>.

When I analyse the profile on my dev machine (debian testing, tuna v0.3.6), I get only 3 entries in the profile:

root0.000 s (100.0%)
~::0::<method 'disable' of '_lsprof.Profiler' objects>0.000 s (100.0%)
~::0::<method 'disable' of '_lsprof.Profiler' objects>::self0.000 s (100.0%)

**Comment by nschloe** [comment]
Perhaps your profile only contains this much data. Impossible to tell without looking at it.

**Comment by ensonic** [comment]
Here is the profile. Can it be that my python version on the device is too old?
[program.prof.gz](https://github.com/nschloe/tuna/files/4239718/program.prof.gz)
