### ISSUE TITLE
Alternate port

### ISSUE THREAD

**Issue by QuLogic** [nschloe/tuna#65]
If I want to compare two files, I might open tuna twice. But I get `OSError: [Errno 98] Address already in use`. It would be nice it if it a) picked some other (random, possibly) port and b) had a CLI flag to pick a specific port.

**Comment by nschloe** [comment]
You probably have an old version. tuna checks for open ports and takes a free one by default. If this doesn't work for you, use the `-p` option.

**Comment by QuLogic** [comment]
Indeed, I must have had it installed already, and not passed `--upgrade`. This does work with 0.4.0.
