### ISSUE TITLE
Is there any plan to support a line and cell magics for Jupyter/Lab notebook?

### ISSUE THREAD

**Issue by dclong** [nschloe/tuna#72]
It would be great and make things really convenient if tuna can support magics for notebook since many Python users are heavily leverage notebooks.

**Comment by nschloe** [comment]
I don't know what magics are. That said, tuna is very open to PRs!

**Comment by neighthan** [comment]
I've got a script for this; I'll submit a PR once I finish making it into a proper magic (right now you just have to pass the "cell" content as a string to the function, but it does display properly in an IFrame in the notebook).

**Comment by mazzma12** [comment]
Thanks for the support. It just look to me that it does not work in my jupyter lab as a cell. And I checked in jupyter notebook and it is the same.  Would it be any way to have it open in a new tab ? it might be more convenient then.

Thanks you for what you have done, this is a great tool!

  ![image](https://user-images.githubusercontent.com/23187108/186852720-c88eb502-7040-4eb9-a325-5d61d71f0309.png)

**Comment by sizhky** [comment]
It's just blank for me as well. 
I have raised a new issue here - https://github.com/nschloe/tuna/issues/163
