### ISSUE TITLE
favicon.ico missing error

### ISSUE THREAD

**Issue by robertlugg** [nschloe/tuna#80]
I'm running in Firefox 60.  The server shows the following error:
```
FileNotFoundError: [Errno 2] No such file or directory: '/remote/YYYY/miniconda3/envs/XXX/lib/python3.7/site-packages/tuna/web/favicon.ico'
```
I am not sure what impact it has but I can't see the chart.

**Comment by nschloe** [comment]
No idea why it would look for `favicon.ico`. Does it work in chrome?

**Comment by nschloe** [comment]
Closing for lack of feedback. Feel free to reopen at any time!
